version: '3'
services:
  app:
    build: docker
    volumes:
      - .:/app:cached
      - ./docker/supervisor.conf.d/:/etc/supervisor/conf.d
      - ./docker/nginx.default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app
    ports:
      - "80:80"
    environment:
      - XDEBUG_MODE=debug
      - PHP_IDE_CONFIG=serverName='${APP_NAME}'
      - XDEBUG_CONFIG=client_host=host.docker.internal idekey=PHPSTORM
  mariadb:
    image: mariadb:10.5.9
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - data_mariadb:/var/lib/mysql
  redis:
      image: 'redis:alpine'
      ports:
          - '${FORWARD_REDIS_PORT:-6379}:6379'
      volumes:
          - 'data_redis:/data'
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  data_mariadb:
  data_redis:
